name: Benchmarks
on: workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        ktor: [ 1.5.0, 1.5.1, 1.5.2, 1.5.3 ]
        jvm: [ 8, 11, 15 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.jvm }}
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: allTests -PktorVersion=${{ matrix.ktor }} --info -PskipTests
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: allTests -PktorVersion=${{ matrix.ktor }} --info
